### ISSUE TITLE
Example Not Work

### ISSUE THREAD

**Issue by kaich** [SDWebImage/SDWebImageHEIFCoder#11]
The Example doesn't work fine. The heif images don't display. I test it in iphone 7p and ios 12.1.3.  It often  crashed. Please check it. Thanks!  

Screenshot as below:

**Comment by kaich** [comment]
![IMG_3672](https://user-images.githubusercontent.com/5013020/58759537-705bdf80-855e-11e9-903a-3b09fb6185e0.PNG)

**Comment by kaich** [comment]
![IMG_3672](https://user-images.githubusercontent.com/5013020/58759576-db0d1b00-855e-11e9-933e-1df07ce96528.PNG)

**Comment by dreampiggy** [comment]
@kaich Reproducable only on iPhone real device but not Simulator. A little suck.

Identified this issue because of #10 . I'll provide a fix now.

**Comment by dreampiggy** [comment]
@kaich Fixed now. I've test it on iPhone XR (iOS 12.3.1)

Please upgrade to v0.5.3: https://github.com/SDWebImage/SDWebImageHEIFCoder/releases/tag/0.5.3

**Comment by kaich** [comment]
@dreampiggy  thank you very much. It fixed now.
