### ISSUE TITLE
Build error due to Legacy Build System

### ISSUE THREAD

**Issue by hvsw** [SDWebImage/SDWebImageHEIFCoder#26]
# Context
Currently, you cannot build `master` branch due to `libde265-Xcode` at `1.0.8` due to `Cartfile.resolved` using Legacy Build System which is now deprecated in Xcode 13.4.

I created [this issue](https://github.com/SDWebImage/libde265-Xcode/issues/6) in libde265-Xcode asking to release a new version in Carthage so this project can use it.

Workaround: specify dependency to point to at least [43a87a1bef850fed5646875d2e965e349ceef3aa](https://github.com/SDWebImage/libde265-Xcode/commit/43a87a1bef850fed5646875d2e965e349ceef3aa).

# Steps to repro
1. `git clone git@github.com:SDWebImage/SDWebImageHEIFCoder.git`
3. `carthage update --platform iOS`

```
 henrique@Henrique-Valcanaia-MacBook-Pro: ~/Developer/SDWebImageHEIFCoder: master: carthage update --platform iOS
*** Fetching libheif-Xcode
*** Fetching SDWebImage
*** Fetching libde265-Xcode
*** Checking out SDWebImage at "5.12.5"
*** Checking out libde265-Xcode at "1.0.8"
*** Checking out libheif-Xcode at "1.9.0"
*** xcodebuild output can be found in /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/carthage-xcodebuild.dlsvI3.log
*** Building scheme "libde265-iOS" in libde265.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/henrique/Developer/SDWebImageHEIFCoder/Carthage/Checkouts/libde265-Xcode/libde265.xcodeproj -scheme libde265-iOS -configuration Release -derivedDataPath /Users/henrique/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4_13F17a/libde265-Xcode/1.0.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/libde265-Xcode SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/henrique/Developer/SDWebImageHEIFCoder/Carthage/Checkouts/libde265-Xcode)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/xp/l3qg7cxs1kg8hqy4lxd4dpj40000gn/T/carthage-xcodebuild.dlsvI3.log
```

**Comment by dreampiggy** [comment]
The lib\*  C library, should match the upstream version. So I think I can only fix the new version, however libdav1d seems 2 years no new commit :(

The libheif and HEICoder can bump the version and fix this.

And, Carthage support is no maintainess for long-time from 2020...SwiftPM and CocoaPods is the preferred way

**Comment by dreampiggy** [comment]
A tricky way is to release a libde265 1.0.9-beta.

I found that HEIFCoder and libheif does not contains the wrong Xcode settings

**Comment by dreampiggy** [comment]
The root reason is `libde265`

`HEIFCoder` -> `libheif` -> `libde265`

Pushed: https://raw.githubusercontent.com/CocoaPods/Specs/3c007f412cd28c1447c39c429604ceb55c2cee56/Specs/1/0/4/libde265/1.0.9-beta/libde265.podspec.json

**Comment by dreampiggy** [comment]
You just need to upgrde the libde265, ensure it's pointed to 1.0.9-beta +

**Comment by hvsw** [comment]
Thank you for the fast response!
