### ISSUE TITLE
animated Heic image can not play with animation

### ISSUE THREAD

**Issue by tangxc** [SDWebImage/SDWebImageHEIFCoder#28]
I have a animated Heic image. then I use ImageIO to decode it,  it could return image that has many images. But when I use SDWebImageHEIFCoder decode it, it can not play with animation, the images is nil. 

there is the code:
```
NSString *imagePath = [[NSBundle mainBundle] pathForResource:@"ll_interaction_heifenc" ofType:@"heic"];
NSData *imageData = [NSData dataWithContentsOfFile:imagePath];
self.imageView.image = [UIImage sd_imageWithData:imageData];
```

I used iPhone 12 ProMax, iOS 15.2. I had created the heic animated image by ImageMagick. `convert *.png ll_interaction_heifenc.heic`

**Comment by dreampiggy** [comment]
>  when I use SDWebImageHEIFCoder decode it, it can not play with animation, the images is nil.

Can you try to use the `SDAnimatedImage(data: heicsData)` ?

Then check the animatedImage's `animationFrameCount` ?

**Comment by dreampiggy** [comment]
The HEIFCoder Demo contains a animated HEICS demo, you can have a try and change that into your heics file as well.

Demo code: https://github.com/SDWebImage/SDWebImageHEIFCoder/blob/master/Example/SDWebImageHEIFCoder/SDViewController.m#L24

url: http://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic

I guess this is some decoding related issue (means, `libheif` is for blame), not something code logic error.

**Comment by dreampiggy** [comment]
If you can, upload your heics image, and I can ask for libheif's author for help

And, you can also open your heics in `Safari` on Mac, can Safari show animation ? If not, I guess this maybe the issues in your image file itself, not the coder ?

**Comment by tangxc** [comment]
Thank you for your help.

My heic can not play animated in Safari on My Mac. I had created it by ImageMagick, Maybe it has some errors.

I download this heic image <http://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic> . It also can not be played with the code.
```
NSString *imagePath = [[NSBundle mainBundle] pathForResource:@"starfield_animation" ofType:@"heic"];
NSData *imageData = [NSData dataWithContentsOfFile:imagePath];
UIImage *image = [UIImage sd_imageWithData:imageData]; // image.images = nil
UIImageView *imageView = ...;
imageView.image = image;

SDAnimatedImage *image = [[SDAnimatedImage alloc] initWithData:imageData]; // use this code, image=nil
```

There is my test heic image's url:
<https://github.com/tangxc/resources_repo/blob/main/ll_interaction_heifenc.heic>
<https://github.com/tangxc/resources_repo/blob/main/ll_interaction_heic.heic>

Thanks.

**Comment by dreampiggy** [comment]
How did you store the image file into NSBundle ? Please pay attention now to add that into `Assets Catalog` (Means, the `Assets.car`)

Or can you directlly using NSURLSession to download data and do the same testing ?

**Comment by dreampiggy** [comment]
Because as my local machine, I can see the animation in HEIFCoder' demo here.

**Comment by tangxc** [comment]
![image](https://github.com/SDWebImage/SDWebImageHEIFCoder/assets/17044959/9f977b8b-0860-41ba-b949-882b0c80e65d)
I just dragged it into my project. You mean I need add it into Assets Catalog. I did it as the picture below, load image is nil：
![image](https://github.com/SDWebImage/SDWebImageHEIFCoder/assets/17044959/a2665073-7dae-4609-8545-ffe531ddc15e)
![image](https://github.com/SDWebImage/SDWebImageHEIFCoder/assets/17044959/9cb86d26-fff4-43f6-9bc5-b1c7ff3d1a7c)

**Comment by tangxc** [comment]
> Because as my local machine, I can see the animation in HEIFCoder' demo here.

Are you use my heic image?

**Comment by tangxc** [comment]
I had run SDWebImageHEIFCoder Example already. The animated HEIC URL still play without animation <http://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic>. I don't know what's wrong with it. My test  machine  is iPhone 12 ProMax, iOS 15.2.

**Comment by dreampiggy** [comment]
Found my comments years ago...Seems libheif does not support HEICs animation ?😂

![image](https://github.com/SDWebImage/SDWebImageHEIFCoder/assets/6919743/406346f5-31e9-4a15-8b65-9c8f2e5bca25)


But Apple's ImageIO supports this. You can test the same image using the SDWebImage demo, or change code in `AppDelegate.m`

```objc
// changes these 2 lines into this, which use Apple's ImageIO (close-sourced, OS vendored)
SDImageHEICCoder *AppleHEICoder = [SDImageHEICCoder sharedCoder];
[[SDImageCodersManager sharedManager] addCoder:AppleHEICoder];
```

**Comment by dreampiggy** [comment]
@tangxc See:
https://github.com/strukturag/libheif/issues/949
https://github.com/strukturag/libheif/issues/377

**Comment by dreampiggy** [comment]
Maybe I can have a test again using the API from libheif like  `heif_context_get_number_of_top_level_images` with your image sample, tomorrow

But I remember 3 years ago, this API for that Nokia animated HEIC ( http://nokiatech.github.io/heif/content/image_sequences/starfield_animation.heic) always return 1....

😣And there are no any `animated`, `loopcount`, or other related words in header `heif.h`. I think, they don't support animation at all.

---

Yes, even for this `starfield_animation.heic`, libheif still report only 1 primary image...And no other API about the frame count information:

![1](https://github.com/SDWebImage/SDWebImageHEIFCoder/assets/6919743/5340af9c-e756-45c9-82e8-3960506e861b)

Test on the libheif 1.16.2 (latest actually....) with de265 codec.

**Comment by dreampiggy** [comment]
See: https://www.dirk-farin.net/software/libheif/index.html

> libheif decodes and generates all conformant still-image HEIF/AVIF files, including HDR, and uses the color transformation matrices specified in the color profile. The HEIF decoder makes use of [libde265](https://www.dirk-farin.net/software/libde265). For encoding, x265 is used. AVIF uses either libaom or dav1d for decoding and libaom or rav1e for encoding.

Only `Still Image` (static), no `Image Sequence` (animated)

**Comment by tangxc** [comment]
> Found my comments years ago...Seems libheif does not support HEICs animation ?😂
> 
> ![image](https://user-images.githubusercontent.com/6919743/278416003-406346f5-31e9-4a15-8b65-9c8f2e5bca25.png)
> 
> But Apple's ImageIO supports this. You can test the same image using the SDWebImage demo, or change code in `AppDelegate.m`
> 
> ```objc
> // changes these 2 lines into this, which use Apple's ImageIO (close-sourced, OS vendored)
> SDImageHEICCoder *AppleHEICoder = [SDImageHEICCoder sharedCoder];
> [[SDImageCodersManager sharedManager] addCoder:AppleHEICoder];
> ```

Thank you very much. 

I have tried SDImageHEICCoder and found it works, my heic image and the starfield_animation.heic all can play with animation. And the SDImageHEICCoder's  API is available with  ios 13.0.

**Comment by dreampiggy** [comment]
`SDImageHEICCoder's` is just wrapper for Apple's ImageIO system framework. And it ship with iOS 13+/macOS 11

I didn't find anything in open-source community about the HEIC sequence support. Even Chrome on Mac itself use Apple's ImageIO 😂 (And old version like macOS 10.15 does not support HEIC)

**Comment by tangxc** [comment]
Maybe it was truth. Thanks again.
